name: mifugocare
description: Mobile-Based Computer Vision for Livestock Disease Detection - AI-powered livestock health monitoring and disease diagnosis system for farmers in Kenya and East Africa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # Supabase
  supabase_flutter: ^2.5.1
  
  # Authentication (for Google Sign-In with Supabase)
  google_sign_in: ^6.2.1
  
  # Camera & Image
  camera: ^0.10.5+7
  image_picker: ^1.0.7
  image: ^3.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # ML & TensorFlow Lite for Disease Detection
  # tflite_flutter: ^0.9.0
  # tflite_flutter_helper: ^0.3.1
  # Note: ML packages temporarily disabled due to dependency conflicts
  # App will run without ML - add these back later for disease detection
  
  # Local Database
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  
  # UI Enhancements
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  
  # Other
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    # Livestock Disease Detection ML Model & Labels
    - assets/models/
    - assets/disease_labels.txt
    
    # App Logos & Images (your existing images)
    - images/
    
    # Additional Assets
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  # Note: Using Google Fonts, so custom fonts are optional
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
